### ISSUE TITLE
Card items missing spacing in Arabic version 

### ISSUE THREAD

**Issue by DarwishMenna** [pg-irc/Arrival-Advisor-Website#12]
**Describe the issue**
Card Items in Arabic version is missing spacing between them
**To Reproduce**
1. Go to HomePage (Arabic version)
2. Scroll down to Cards list

**Expected behavior**
<img width="1214" alt="Screen Shot 2019-03-15 at 4 16 48 PM" src="https://user-images.githubusercontent.com/45855609/54466631-c8dcc700-473d-11e9-984a-6e96205d0c6f.png">

**Screenshots**
<img width="1256" alt="Screen Shot 2019-03-15 at 4 13 55 PM" src="https://user-images.githubusercontent.com/45855609/54466618-b498ca00-473d-11e9-801a-49fc1014bce3.png">

**Browser name (please complete the following information):**
 - chrome

**Comment by beni4** [comment]
Fixed
