### ISSUE TITLE
Repeater Bug - Field original value not correct.

### ISSUE THREAD

**Issue by beni4** [pg-irc/Arrival-Advisor-Website#132]
**Describe the issue**
The Arrival Advisor website currently uses Advanced Custom Fields PRO and WPML Plugins. 

The plugins cannot communicate properly when the repeater function is in use, this means that the "field value original language" does not show the correct corresponding English text, which makes the process of translating more complicated.

The field value original language either appears empty or has the incorrect value for the field. 

When the repeater function is not in use, for say a simple string of text, this error does not occur and the correct English is displayed under the translated language.

**Expected behavior**
Under every Field there is an "field value original language" which represents the content on the English page, this makes finding translated text easier for English speakers as they have a reference point. 

**Screenshots**
This is a screenshot below of the issue working correctly on a single string, with the correct value underneath. 
<img width="920" alt="Screenshot 2019-05-28 at 17 57 38" src="https://user-images.githubusercontent.com/24415918/58498496-762c7c00-817e-11e9-8514-c1c4dc307025.png">

Below is a screenshot of the value not being transferred to the corresponding field, this is within a repeater function. As you can see for a non native, it would be difficult to identify which member of the team this is etc
<img width="905" alt="Screenshot 2019-05-28 at 17 58 48" src="https://user-images.githubusercontent.com/24415918/58498551-8fcdc380-817e-11e9-8862-4e83be9cf80e.png">

**Additional context**

**Comment by CarlieNishi** [comment]
Hi @ArtiBPG and @cherrielam 

Did Affinity Bridge have any solutions to this issue? Please let us know.

**Comment by CarlieNishi** [comment]
Closing this task.
