### ISSUE TITLE
Testimonials position moves when clicking on the arrow

### ISSUE THREAD

**Issue by DarwishMenna** [pg-irc/Arrival-Advisor-Website#14]
**Describe the issue**
Testimonials position changes when clicking on the (next - prev) arrows

**To Reproduce**
1. Go to Homepage
2. Scroll down to testimonials section
3. Click on the next arrow

**Expected behavior**
Testimonials' position shouldn't change

**Browser name (please complete the following information):**
 - chrome

**Comment by beni4** [comment]
Resolved, testimonials no longer move.
