### ISSUE TITLE
Arabic- missing strings ready for import

### ISSUE THREAD

**Issue by ArtiBPG** [pg-irc/Arrival-Advisor-Website#16]
Text in all tabs named "Additional Translations Mar 15- Ready" can be imported into the app/website
[Arabic](https://docs.google.com/spreadsheets/d/142D66QsaQEbwDjVOsHX6z2Nw55WbNf6vfFKnLS-HMC0/edit?usp=sharing)

**Comment by CarlieNishi** [comment]
@ArtiBPG are you able to share that "Additional Translations Mar 15- Ready" document with us? We reviewed this copy deck but don't see any additional translations https://docs.google.com/spreadsheets/d/13rmWEHBlceg3Gs0PMfemcaUhXPE1yg0cotVcyOWPPo0/edit#gid=2076857657

**Comment by CarlieNishi** [comment]
@cherrielam tagging you in here in case Arti isn't able to share this tab/sheet.

**Comment by ArtiBPG** [comment]
@CarlieNishi they are right here: https://www.screencast.com/t/jYGlf3P4R3f
these are tranlations that were missing from the initial copy that was provided. It has strings for the app and the website, so you can use Ctrl+ F to search for any strings that were missing.

**Comment by CarlieNishi** [comment]
Thanks @ArtiBPG
