### ISSUE TITLE
Lowercase "We can help." for the home page bubble

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/Arrival-Advisor-Website#17]
![Screen Shot 2019-03-19 at 7.45.14 AM.png](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/8323cee2-2bbf-42fa-8488-c7fd315c40e5)

Please amend the home page speech bubble as above ^

**Comment by beni4** [comment]
Resolved

**Comment by cherrielam** [comment]
@beni4 Nitpicky yes but can you please add the period at the end of We can help. ? And bump up the font size or the margins so it looks centered?

**Comment by beni4** [comment]
Done
