### ISSUE TITLE
Design - Logos look stretched vertically

### ISSUE THREAD

**Issue by ArtiBPG** [pg-irc/Arrival-Advisor-Website#2]
**Describe the issue**
Logos look stretched vertically

**To Reproduce**
Go to https://arrivaladvisor.ca/about-us/

**Screenshots**
https://screencast.com/t/GD8YNMc1fL

**Browser name (please complete the following information):**
 - Chrome

**Comment by CarlieNishi** [comment]
Logos have been updated with the most recent ones we have. @cherrielam to review

**Comment by cherrielam** [comment]
WelcomeBC logo in footer still looks distorted. Just realized I never originally shared a white version of the logo to share with you so unsure where the one in the footer was sourced. In any case, please replace with this one: https://drive.google.com/open?id=1NA4azINQvM-OGMflS8x3pR0sfIpIvNOX (PNG) or https://drive.google.com/open?id=163-3jOpLeeUDOqE7PmUEt3nY9x7Eohgx (SVG)

Vancouver Immigration Partnership logo uncentered and too large. I just whipped up a new version with some added padding, please replace: https://drive.google.com/open?id=1B35Rbqnblm8tDec_0xrfbuPoZ_DX10Yd

On the "About Us" page, logos are still distorted. See below:
<img width="800" alt="Screen Shot 2019-03-19 at 7 46 40 AM" src="https://user-images.githubusercontent.com/21990736/54615530-82c48380-4a1b-11e9-8a12-f56f78b5d6b5.png">

I have gone into Inspect to see what the img width is set at... I have now produced lockups of the logo matching the img widths you've set so hopefully you can just do a quick swap (temporary fix, ideally the logos should not distort even if they're not the right img width)

Here's WelcomeBC: https://drive.google.com/open?id=1ZDfvNGUN3LNec8cgOqhE6Q-wD3alKldX
Here's LEAP: https://drive.google.com/open?id=1CcplnIZtzkce1lbdI2RKVDeMVasJI3aa

Also the order of the logos in About Us should be reversed: Google.org, then Leap, then BC

@beni4 @CarlieNishi

**Comment by beni4** [comment]
Made the adjustments. @cherrielam

**Comment by cherrielam** [comment]
@beni4 WelcomeBC logo looks horizontally stretched, likely because it is formatted for 190x70 and you have put it in for 200x70. Can you please amend? 
<img width="1274" alt="Screen Shot 2019-03-19 at 3 36 29 PM" src="https://user-images.githubusercontent.com/21990736/54646604-ce4b5180-4a5c-11e9-8fa1-b51108dbb7be.png">

**Comment by beni4** [comment]
Please update your cache and check that this is still the case, I have not changed any dimensions this morning simply change the image. the dimensions are 200x70 on the code
<img width="727" alt="Screenshot 2019-03-19 at 16 16 08" src="https://user-images.githubusercontent.com/24415918/54648145-5bdd7000-4a62-11e9-9ece-579208da5cc6.png">
x70

**Comment by beni4** [comment]
This was actually changed yesterday when I got a cleaner version on the logo. But I have reverted back to the dimensions needed. Please clear cache and double check this is the case.
