### ISSUE TITLE
Match "Committee" labels in About Us with H4 style on the home page

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/Arrival-Advisor-Website#20]
![Screen Shot 2019-03-19 at 8.21.33 AM.png](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/addb0d54-8873-4b96-b656-2b191232c37e)

"Newcomer Committee" copy - could it use the below style

![Screen Shot 2019-03-19 at 8.21.51 AM.png](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/d41d9004-4a98-4608-bfd9-d7e61410a7d6)

**Comment by beni4** [comment]
Matched.
