### ISSUE TITLE
Make forms non-uppercase

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/Arrival-Advisor-Website#21]
![Screen Shot 2019-03-19 at 8.23.57 AM.png](https://images.zenhubusercontent.com/5823860ee40e5714b1700133/6dc1e567-ad45-4f89-9a1b-254ccfac01e0)

Can we please make this text non-all-uppercase? The message part especially feels obnoxious when it's allcaps.

**Comment by beni4** [comment]
removed the uppercase text, do we want the button to remain uppercase? @cherrielam
