### ISSUE TITLE
Translated videos

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/Arrival-Advisor-Website#32]
Here are the links to the translated videos. @ArtiBPG these are ready for QA. Once they are QA'ed they can be publicly listed. @CarlieNishi @beni4 these can be used for the website

Arabic: https://youtu.be/VDMAGI9mAZw
Chinese Simplified AND Traditional: https://youtu.be/QAD1pab30a8 - same video, has both versions of subtitles
Tagalog: https://youtu.be/KzZnmRk3PSc
Punjabi: https://youtu.be/0MUPGT5zDis
Korean: https://youtu.be/hOYvRYj6EiQ
French: https://youtu.be/-AkIqr173r4

**Comment by CarlieNishi** [comment]
Thanks Cherrie. Confirming that we don't have to reupload all the other languages you linked.
