### ISSUE TITLE
Design - French: E is missing the accent

### ISSUE THREAD

**Issue by ArtiBPG** [pg-irc/Arrival-Advisor-Website#5]
**Describe the issue**
The text looks very squished together as a result the accent on the E is not visible.
Suggestion: Increase character spacing- vertical and horizontal.

**To Reproduce**
Go to https://arrivaladvisor.ca/fr

**Screenshots**
https://screencast.com/t/3wjAOLJAbb0
more squished text: https://screencast.com/t/WM0Lqut0zVbr

**Browser name (please complete the following information):**
Chrome

**Acceptance criteria
The text should have more room so the letters do not look squished and all accents are visible.

**Comment by beni4** [comment]
I think this one has been discussed, but this is an issue with the font that is being used. the accents are all in place from the translations.
