### ISSUE TITLE
FR - Footer - "FEEDBACK & SUPPORT" and "CONTACT US" pages are the same

### ISSUE THREAD

**Issue by ludivinegh** [pg-irc/Arrival-Advisor-Website#85]
**Describe the issue**
The FEEDBACK & SUPPORT and CONTACT US pages are the same. Please confirm whether this is expected.

**To Reproduce**
1. Go to the footer
2. Open the FEEDBACK & SUPPORT page
3. Open the CONTACT US page
4. Compare them

**Expected behavior**
I think FEEDBACK & SUPPORT doesn't display the correct page.

**Screenshots**
FEEDBACK & SUPPORT: http://glbl.me/ttc (URL: https://arrivaladvisor.ca/fr/communiquer-avec-nous/)
CONTACT US: http://glbl.me/ttc (URL: https://arrivaladvisor.ca/fr/communiquer-avec-nous/)

**Browser name (please complete the following information):**
Chrome

**Additional context**

**Comment by ArtiBPG** [comment]
this is as intended, goes to the same contact page.
